#!/bin/bash

make

imagenes=('720p.png' '4K.jpg' '1080p.png')
echo "Resultados de la ejecucion" > resultados.txt;
for item in ${imagenes[@]}
do
    for kernel in `seq 3 2 15`;
    do
	echo "nombre "$item" kernel:"$kernel" hilos: 1" >> resultados.txt;
	(time ./blur-effect $item $kernel ) 2>&1 |grep real >> resultados.txt;
	for hilos in `seq 2 2 16`;
	do
	    echo "hilos:"$hilos >> resultados.txt;
	    (time ./blur-effect $item $kernel $hilos ) 2>&1 | grep real >> resultados.txt;
	     echo "nombre "$item" kernel:"$kernel" hilos:"$hilos;
	done
    done
done
